spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/products/**
        - id: people-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/people/**
        - id: inventory-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/inventory/**
        - id: product-service-openapi
          uri: http://localhost:8083
          predicates:
            - Path=/openapi/product-service/**
          filters:
            - StripPrefix=2
        - id: people-service-openapi
          uri: http://localhost:8082
          predicates:
            - Path=/openapi/people-service/**
          filters:
            - StripPrefix=2
        - id: inventory-service-openapi
          uri: http://localhost:8081
          predicates:
            - Path=/openapi/inventory-service/**
          filters:
            - StripPrefix=2
