spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/products/**
          - id: people-service
            uri: lb://people-service
            predicates:
              - Path=/api/people/**
          - id: inventory-service
            uri: lb://inventory-service
            predicates:
              - Path=/api/inventory/**
          - id: product-service-openapi
            uri: lb://product-service
            predicates:
              - Path=/openapi/product-service/**
            filters:
              - StripPrefix=2
          - id: people-service-openapi
            uri: lb://people-service
            predicates:
              - Path=/openapi/people-service/**
            filters:
              - StripPrefix=2
          - id: inventory-service-openapi
            uri: lb://inventory-service
            predicates:
              - Path=/openapi/inventory-service/**
            filters:
              - StripPrefix=2
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
