spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8083
          predicates:
            - Path=/api/products/**
        - id: people-service
          uri: http://people-service:8082
          predicates:
            - Path=/api/people/**
        - id: inventory-service
          uri: http://inventory-service:8083
          predicates:
            - Path=/api/inventory/**
        - id: product-service-openapi
          uri: http://product-service:8083
          predicates:
            - Path=/openapi/product-service/**
          filters:
            - StripPrefix=2
        - id: people-service-openapi
          uri: http://people-service:8082
          predicates:
            - Path=/openapi/people-service/**
          filters:
            - StripPrefix=2
        - id: inventory-service-openapi
          uri: http://inventory-service:8083
          predicates:
            - Path=/openapi/inventory-service/**
          filters:
            - StripPrefix=2

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
